//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APPLICATIONDB_fa3bfcf9d998484faa5d969985e5086fEntities3 : DbContext
    {
        public APPLICATIONDB_fa3bfcf9d998484faa5d969985e5086fEntities3()
            : base("name=APPLICATIONDB_fa3bfcf9d998484faa5d969985e5086fEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonCar> PersonCars { get; set; }
    }
}
